version: "3"
services:
    db:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 1234
        volumes:
            - "./data/db:/data/db"
    backend:
        depends_on: db
        build: ./backend
        ports:
            - "6969:6969"
        environment:
            DB_URI: "mongodb://db"
